(() => {
  'use strict';

  if (window.__warextTurkishSpellCheckV160) return;
  window.__warextTurkishSpellCheckV160 = true;

  const VERSION='1',BUILD='1.6.0',BASE=window.WarextSpellBaseDirV160||'';
  const states=new WeakMap(),stateList=new Set(),pending=new Map(),listened=new WeakSet();
  let worker=null,workerBroken=false,seq=0,fallback=null;
  const norm=v=>String(v||'').replace(/I/g,'ı').replace(/İ/g,'i').toLocaleLowerCase('tr-TR').trim();
  const uniq=a=>[...new Set(a.filter(Boolean))];
  document.documentElement.dataset.wtscVersion=VERSION;
  document.documentElement.dataset.wtscBuild=BUILD;

  const split=v=>uniq(String(v||'').split(/[\n,;]+/u).map(x=>x.trim()));
  const bool=(v,d=true)=>v==null||v===''?d:!['0','false','off','no'].includes(String(v).toLowerCase());
  const cfg=(()=>{const d=document.getElementById('wtsc-config')?.dataset||{};return{enabled:bool(d.enabled),grammar:bool(d.grammar),punctuation:bool(d.punctuation),underline:bool(d.underline),properNames:bool(d.properNames),informal:bool(d.informal),maxSuggestions:Math.max(1,Math.min(3,Number(d.maxSuggestions||3))),adminWords:split(document.getElementById('wtsc-custom-words')?.textContent),customProperNames:split(document.getElementById('wtsc-custom-proper-names')?.textContent)}})();
  const uid=window.XF?.config?.userId??window.XF?.config?.user_id??'guest';
  const dk=`wtsc:user-dictionary:${location.host}:${uid}`,ik=`wtsc:ignored:${location.host}:${uid}`;
  const read=(s,k)=>{try{const v=JSON.parse(s.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch(_){return[]}};
  let userWords=read(localStorage,dk),ignoredWords=read(sessionStorage,ik);
  const save=()=>{try{localStorage.setItem(dk,JSON.stringify(uniq(userWords.map(norm))))}catch(_){}try{sessionStorage.setItem(ik,JSON.stringify(uniq(ignoredWords.map(norm))))}catch(_){}};
  const options=x=>({grammar:cfg.grammar,punctuation:cfg.punctuation,underline:cfg.underline,properNames:cfg.properNames,informal:cfg.informal,maxSuggestions:cfg.maxSuggestions,adminWords:cfg.adminWords,customProperNames:cfg.customProperNames,userWords,ignoredWords,maxIssues:50,...x});

  function load(file,check){return new Promise((res,rej)=>{if(check?.())return res();const src=BASE+file,old=[...document.scripts].find(x=>x.src===src||x.dataset.wtscAsset===file);if(old){old.addEventListener('load',res,{once:true});old.addEventListener('error',rej,{once:true});return}const s=document.createElement('script');s.src=src;s.async=false;s.dataset.wtscAsset=file;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
  async function ensureFallback(){if(!fallback)fallback=(async()=>{await load('dictionary-v160.js',()=>!!window.WarextTurkishSpellEngineV160);await load('rules-v160.js',()=>!!window.WarextTurkishRulesV160);if(!window.WarextTurkishRulesV160)throw new Error('rules missing')})();return fallback}
  function makeWorker(){if(worker||workerBroken||typeof Worker==='undefined')return worker;try{worker=new Worker(BASE+'worker-v160.js');worker.onmessage=e=>{const d=e.data||{},p=pending.get(d.id);if(!p)return;pending.delete(d.id);d.type==='error'?p.reject(new Error(d.message||'worker')):p.resolve(d.result||d)};worker.onerror=()=>{workerBroken=true;for(const p of pending.values())p.reject(new Error('worker'));pending.clear();try{worker.terminate()}catch(_){}worker=null}}catch(_){workerBroken=true}return worker}
  async function analyze(text,payload){const w=makeWorker();if(w){const id=++seq;try{return await new Promise((resolve,reject)=>{const t=setTimeout(()=>{pending.delete(id);reject(new Error('timeout'))},6000);pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});w.postMessage({id,type:'analyze',text,payload})})}catch(_){workerBroken=true;try{worker?.terminate()}catch(_){}worker=null}}await ensureFallback();return window.WarextTurkishRulesV160.analyze(text,payload)}

  function style(){if(document.getElementById('wtsc-style-v160'))return;const s=document.createElement('style');s.id='wtsc-style-v160';s.textContent='.wtsc-suggestions{display:none;margin:7px 0 3px;width:100%;box-sizing:border-box;border:1px solid rgba(127,127,127,.25);border-radius:9px;padding:7px;background:rgba(127,127,127,.04)}.wtsc-suggestions.is-active{display:block}.wtsc-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.wtsc-suggestion{appearance:none;min-width:0;border:1px solid rgba(127,127,127,.32);background:rgba(127,127,127,.08);color:inherit;border-radius:7px;padding:8px 10px;font:inherit;font-size:13px;text-align:left;cursor:pointer}.wtsc-label{display:block;font-size:10px;opacity:.68;margin-bottom:3px;text-transform:uppercase}.wtsc-value{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:600}.wtsc-message{font-size:11px;opacity:.75;padding:0 2px 6px}.wtsc-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px;padding-top:6px;border-top:1px solid rgba(127,127,127,.2)}.wtsc-action{border:0;background:transparent;color:inherit;opacity:.75;padding:4px 6px;font:inherit;font-size:11px;cursor:pointer;border-radius:5px}.wtsc-action:hover{opacity:1;background:rgba(127,127,127,.1)}.wtsc-dialog{border:1px solid rgba(127,127,127,.35);border-radius:10px;padding:0;max-width:min(520px,92vw);width:100%;color:inherit;background:Canvas}.wtsc-dialog::backdrop{background:rgba(0,0,0,.35)}.wtsc-row{display:flex;justify-content:space-between;gap:10px;padding:8px 14px;border-bottom:1px solid rgba(127,127,127,.12)}::highlight(wtsc-spelling){text-decoration:underline wavy #d33}::highlight(wtsc-grammar){text-decoration:underline wavy #d98200}::highlight(wtsc-punctuation){text-decoration:underline dotted #7b61ff}::highlight(wtsc-capitalization){text-decoration:underline wavy #2b7de9}::highlight(wtsc-proper){text-decoration:underline wavy #9b59b6}::highlight(wtsc-style){text-decoration:underline dashed #6b7280}@media(max-width:650px){.wtsc-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
  const isTitle=e=>e instanceof HTMLInputElement&&e.name==='title';
  const isText=e=>e instanceof HTMLTextAreaElement&&(e.name==='message'||e.dataset.originalName==='message'||e.matches('textarea.js-editor[data-xf-init~="editor"]'));
  const isRich=e=>e instanceof HTMLElement&&e.isContentEditable&&(e.classList.contains('fr-element')||!!e.closest('.fr-box'));
  function barFor(el){const owner=isRich(el)?el.closest('.fr-box')||el:el;if(owner.__wtscBar?.isConnected)return owner.__wtscBar;const b=document.createElement('div');b.className='wtsc-suggestions';b.setAttribute('role','listbox');if(isRich(el)){const box=el.closest('.fr-box')||el;box.parentElement?.querySelectorAll('.wtsc-suggestions').forEach(x=>x.remove());box.insertAdjacentElement('afterend',b)}else(el.closest('.inputGroup')||el.parentElement)?.insertAdjacentElement('afterend',b);owner.__wtscBar=b;return b}
  function nodes(root){const a=[],w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))a.push(n);return a}
  function richState(el){const s=getSelection();if(!s?.rangeCount||!s.isCollapsed)return null;const r=s.getRangeAt(0);if(!el.contains(r.startContainer))return null;const ns=nodes(el);let text='',caret=null;for(const n of ns){if(n===r.startContainer)caret=text.length+Math.min(r.startOffset,n.nodeValue?.length||0);text+=n.nodeValue||''}if(caret==null){try{const q=document.createRange();q.selectNodeContents(el);q.setEnd(r.startContainer,r.startOffset);caret=q.toString().length}catch(_){caret=text.length}}return{text,caret}}
  function docState(el){if(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement){const text=el.value||'';return{text,caret:Math.max(0,Math.min(text.length,el.selectionStart??text.length))}}return isRich(el)?richState(el):null}
  function rangeAt(root,start,end){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let p=0,a=null,b=null,ao=0,bo=0,n;while((n=w.nextNode())){const l=n.nodeValue?.length||0;if(!a&&start>=p&&start<=p+l){a=n;ao=start-p}if(end>=p&&end<=p+l){b=n;bo=end-p;break}p+=l}if(!a||!b)return null;const r=document.createRange();r.setStart(a,ao);r.setEnd(b,bo);return r}
  function replace(el,issue,value){if(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement){el.value=el.value.slice(0,issue.start)+value+el.value.slice(issue.end);const p=issue.start+value.length;el.setSelectionRange?.(p,p);el.dispatchEvent(new Event('input',{bubbles:true}));el.focus();return}const r=rangeAt(el,issue.start,issue.end);if(!r)return;r.deleteContents();const n=document.createTextNode(value);r.insertNode(n);const q=document.createRange();q.setStartAfter(n);q.collapse(true);const s=getSelection();s.removeAllRanges();s.addRange(q);el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()}
  function changed(oldText,newText,caret){if(!oldText)return{start:Math.max(0,caret-1),end:caret};let a=0,ol=oldText.length,nl=newText.length;while(a<ol&&a<nl&&oldText[a]===newText[a])a++;let b=0;while(b<ol-a&&b<nl-a&&oldText[ol-1-b]===newText[nl-1-b])b++;return{start:a,end:Math.max(a,nl-b)}}

  function hide(b){b.classList.remove('is-active');b.textContent=''}
  function action(parent,text,fn){const b=document.createElement('button');b.type='button';b.className='wtsc-action';b.textContent=text;b.onmousedown=e=>e.preventDefault();b.onclick=fn;parent.appendChild(b)}
  function dialog(st){let d=document.getElementById('wtsc-dictionary-dialog');if(!d){d=document.createElement('dialog');d.id='wtsc-dictionary-dialog';d.className='wtsc-dialog';document.body.appendChild(d)}d.textContent='';const h=document.createElement('div');h.className='wtsc-row';h.textContent='Kullanıcı sözlüğüm';d.appendChild(h);const words=uniq(userWords.map(norm)).sort((a,b)=>a.localeCompare(b,'tr'));if(!words.length){const e=document.createElement('div');e.className='wtsc-row';e.textContent='Henüz özel kelime eklenmedi.';d.appendChild(e)}for(const word of words){const r=document.createElement('div');r.className='wtsc-row';const x=document.createElement('span');x.textContent=word;const b=document.createElement('button');b.type='button';b.className='wtsc-action';b.textContent='Kaldır';b.onclick=()=>{userWords=userWords.filter(v=>norm(v)!==word);save();r.remove();st.schedule(0,true)};r.append(x,b);d.appendChild(r)}const f=document.createElement('div');f.className='wtsc-row';action(f,'Kapat',()=>d.close?.());d.appendChild(f);d.showModal?.()||d.setAttribute('open','')}
  function render(st,issues){const b=st.bar;hide(b);const focus=issues.find(i=>i.start<=st.caret&&st.caret<=i.end)||issues[0];if(focus?.message){const m=document.createElement('div');m.className='wtsc-message';m.textContent=focus.message;b.appendChild(m)}const g=document.createElement('div');g.className='wtsc-grid';const seen=new Set();for(const issue of issues){for(const v of issue.suggestions||[]){const k=norm(v);if(!k||seen.has(k))continue;seen.add(k);const x=document.createElement('button');x.type='button';x.className='wtsc-suggestion';x.innerHTML='';const l=document.createElement('span');l.className='wtsc-label';l.textContent=issue.label||issue.category||'Öneri';const q=document.createElement('span');q.className='wtsc-value';q.textContent=v;x.append(l,q);x.onmousedown=e=>e.preventDefault();x.onclick=()=>{replace(st.el,issue,v);hide(b);st.schedule(20,true)};g.appendChild(x);if(g.childElementCount>=cfg.maxSuggestions)break}if(g.childElementCount>=cfg.maxSuggestions)break}if(g.childElementCount)b.appendChild(g);const a=document.createElement('div');a.className='wtsc-actions';const word=norm(focus?.word||'');if(word&&/^[a-zçğıöşüâîû]+$/u.test(word)&&['spelling','grammar'].includes(focus.category)){action(a,'Yoksay',()=>{ignoredWords=uniq([...ignoredWords,word]);save();st.schedule(0,true)});action(a,'Sözlüğe ekle',()=>{userWords=uniq([...userWords,word]);ignoredWords=ignoredWords.filter(x=>norm(x)!==word);save();st.schedule(0,true)})}action(a,'Sözlüğüm',()=>dialog(st));b.appendChild(a);b.classList.add('is-active')}

  function highlights(){if(typeof CSS==='undefined'||!CSS.highlights||typeof Highlight==='undefined')return;for(const c of ['spelling','grammar','punctuation','capitalization','proper','style']){const ranges=[];for(const st of [...stateList]){if(!st.el?.isConnected){stateList.delete(st);continue}ranges.push(...(st.ranges?.[c]||[]))}const n=`wtsc-${c}`;ranges.length?CSS.highlights.set(n,new Highlight(...ranges)):CSS.highlights.delete(n)}}
  function mark(st,issues){st.ranges={};if(cfg.underline&&isRich(st.el)){for(const i of issues){if(i.start===i.end)continue;const r=rangeAt(st.el,i.start,i.end);if(!r)continue;const c=['spelling','grammar','punctuation','capitalization','proper','style'].includes(i.category)?i.category:'spelling';(st.ranges[c]||=[]).push(r)}}highlights()}

  function attach(el){if(!cfg.enabled||!el||states.has(el)||!(isTitle(el)||isText(el)||isRich(el)))return states.get(el)||null;const st={el,bar:barFor(el),last:'',ranges:{},caret:0,schedule:null};let timer=0,run=0;st.schedule=(delay=180,force=false)=>{clearTimeout(timer);timer=setTimeout(async()=>{const id=++run,d=docState(el);if(!d)return;st.caret=d.caret;const ch=force?{start:d.caret,end:d.caret}:changed(st.last,d.text,d.caret);try{const r=await analyze(d.text,{caret:d.caret,changedStart:ch.start,changedEnd:ch.end,options:options({isTitle:isTitle(el)})});if(id!==run)return;st.last=d.text;const issues=r?.issues||[];mark(st,issues);issues.length?render(st,issues):hide(st.bar);document.documentElement.dataset.wtscStatus='local-ok'}catch(_){if(id!==run)return;hide(st.bar);st.bar.textContent='Yazım denetimi motoru yüklenemedi.';st.bar.classList.add('is-active');document.documentElement.dataset.wtscStatus='engine-error'}},delay)};states.set(el,st);stateList.add(st);el.dataset.wtscBound='1';el.addEventListener('input',()=>st.schedule(260),{passive:true});el.addEventListener('keyup',()=>st.schedule(160),{passive:true});el.addEventListener('click',()=>st.schedule(25,true),{passive:true});el.addEventListener('focus',()=>st.schedule(50,true),{passive:true});st.schedule(60,true);return st}
  function surface(e){return e?.ed?.el||e?.editor?.ed?.el||e?.detail?.ed?.el||null}
  function bind(t){if(!(t instanceof HTMLTextAreaElement))return;if(!listened.has(t)){listened.add(t);const f=e=>{const x=surface(e);if(x instanceof HTMLElement)attach(x)?.schedule(20,true)};window.XF?.on?XF.on(t,'editor:init',f):t.addEventListener('editor:init',f)}try{const x=window.XF?.Element?.getHandler?.(t,'editor')?.ed?.el;if(x instanceof HTMLElement){attach(x);return}}catch(_){}if(!t.parentElement?.querySelector?.('.fr-box .fr-element[contenteditable="true"]')&&isText(t)&&t.offsetParent!==null)attach(t)}
  function scan(root=document){if(!cfg.enabled)return;if(root instanceof HTMLTextAreaElement)bind(root);root.querySelectorAll?.('textarea.js-editor[data-xf-init~="editor"],textarea[name="message"],textarea[data-original-name="message"]').forEach(bind);if(root instanceof HTMLInputElement&&isTitle(root))attach(root);root.querySelectorAll?.('input[name="title"]').forEach(attach);if(root instanceof HTMLElement&&isRich(root))attach(root);root.querySelectorAll?.('.fr-element[contenteditable="true"]').forEach(attach)}
  function boot(){style();if(!cfg.enabled){document.documentElement.dataset.wtscStatus='disabled';return}makeWorker();if(window.XF?.on)XF.on(document,'editor:init',e=>{const x=surface(e);if(x instanceof HTMLElement)attach(x)?.schedule(20,true)});scan();document.addEventListener('focusin',e=>{if(e.target instanceof HTMLTextAreaElement)bind(e.target);const x=e.target?.closest?.('.fr-element[contenteditable="true"],textarea.js-editor,textarea[name="message"],input[name="title"]');if(x instanceof HTMLElement)attach(x)?.schedule(30,true)},true);new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n instanceof Element)scan(n)}).observe(document.body,{childList:true,subtree:true});let n=0;const t=setInterval(()=>{scan();if(++n>=10)clearInterval(t)},500)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
